version = 0.1

[default.deploy.parameters]
stack_name = "aws-sam-poc"
resolve_s3 = true
s3_prefix = "aws-sam-poc"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=dev"
confirm_changeset = true

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.sync.parameters]
watch = true

# Staging environment
[staging.deploy.parameters]
stack_name = "aws-sam-poc-staging"
resolve_s3 = true
s3_prefix = "aws-sam-poc-staging"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=staging"
confirm_changeset = true

# Production environment
[prod.deploy.parameters]
stack_name = "aws-sam-poc-prod"
resolve_s3 = true
s3_prefix = "aws-sam-poc-prod"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=prod"
confirm_changeset = true
